import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNavbar from "@/lib/component/Navbar/mainNavbar/MainNavbar";
import LogInMainMenu from "@/lib/component/Navbar/mainNavbar/LogInMenu";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const cookieStore = await cookies()
  const token = cookieStore.get('token')?.value
  return (
    <html lang="en">
      <body>
        <div className="pt-18">
          {
            token?<LogInMainMenu/>:<MainNavbar/>
          }
         
        </div>
        {children}
      </body>
    </html>
  );
}
